services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pcpartsdb'
      - 'POSTGRES_PASSWORD=pcparts_password'
      - 'POSTGRES_USER=pcparts_user'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    volumes:
      - 'redis_data:/data'
    restart: unless-stopped

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10427:8080'
    depends_on:
      - postgres
      - redis
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pcpartsdb'
      - 'SPRING_DATASOURCE_USERNAME=pcparts_user'
      - 'SPRING_DATASOURCE_PASSWORD=pcparts_password'
      - 'SPRING_PROFILES_ACTIVE=docker'
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

